# Config dedicated for module A
# All the resources must be prefixed with `module-a-` to avoid conflicts

version: 2.1

orbs:
  module-frontend-aws-ecr: circleci/aws-ecr@6.15.3

jobs:
  aws-dummy-frontend:
    steps:
      - run: echo "Frontend deploy"
  deploy-frontend:
    docker:
      - image: cimg/node:14.18.2
    steps:
      - run: echo "Deployed Frontend"

workflows:
  frontend-workflow:
    jobs:
      - aws-dummy-frontend:
          name: aws-ecr-image-frontend
      - deploy-frontend:
          requires:
            - aws-ecr-image-frontend
