# CircleCI 2.1 configuration file
# Using the Orb aws-ecr to push the Docker Image to ECR: https://circleci.com/orbs/registry/orb/circleci/aws-ecr
# Using the Orb sonarcloud to analyse project with SonarQube: https://circleci.com/developer/orbs/orb/sonarsource/sonarcloud

version: 2.1

orbs:
  aws-ecr: circleci/aws-ecr@6.15.3
  sonarcloud: sonarsource/sonarcloud@1.0.2
  ms-teams: cloudradar-monitoring/ms-teams@0.0.1

parameters:
  test:
    type: string
    default: acv

executors:
  node-executor:
    docker:
      - image: cimg/node:14.18.2

base_build_job_config: &base_build_job_config
  context: SonarCloud

base_job_config: &base_job_config
  <<: *base_build_job_config

workflows:
  version: 2
  contentpool2-ci-frontend:
    jobs:
      - build:
          <<: *base_build_job_config
      - aws-dummy-frontend:
          <<: *base_job_config
          name: aws-ecr-image-backend
          requires:
            - build
      - deploy-frontend:
          <<: *base_job_config
          requires:
            - aws-ecr-image-frontend

commands:
  spinnaker-deployment:
    parameters:
      spinnaker-module:
        type: string
    steps:
      - run:
          name: Dummy spinnaker
          command: echo "dummy spinnaker"

jobs:
  build-frontend:
    executor: node-executor
    steps:
      - checkout
      - restore_cache:
          keys:
            # Always use the same npm-cache - no matter the package.json etc.
            - v1-dependencies-cache
      - run:
          name: Define current base
          command: |
              BASE=main
              if [ "$CIRCLE_BRANCH" = "main" ]; then
                BASE=main~1
              elif [ "$CIRCLE_BRANCH" = "production" ]; then
                BASE=production~1
              fi
              echo "export BASE=$BASE" >> $BASH_ENV
              echo $BASE
      - run:
          name: Create .npmrc
          command: cp .npmrc.template .npmrc
      - run:
          name: Install node dependencies
          # Set the cache folder to be the .npm folder in the project root
          # before installing dependencies
          command: |
            npm set cache .npm
            npm ci
      - run:
          name: Post install
          command: npm run postinstall
      - restore_cache:
          keys:
            # Computational cache used by nx and Angular
            - v1-computational-cache
      - run:
          name: Create a dummy .env file to be able to run the tests
          command: touch .env
      - run:
          name: Run Linter on affected projects
          command: |
            echo $BASE
            npm lint --maxWarnings=100
      - run:
          name: Test affected projects
          command: npm test --coverage --maxWorkers=1
      - run:
          name: Build affected frontend / backend
          command: npm build --prod
      - run:
          name: Build server side of frontend
          command: echo "build server"
      - run:
          name: Store the version
          command: |
            export BUILD_VERSION=$(git rev-parse --abbrev-ref HEAD)-$(git rev-parse --short HEAD)
            echo "$BUILD_VERSION-$CIRCLE_BUILD_NUM" > VERSION
            echo "Stored version " `cat VERSION`
      - save_cache:
          # Save the npm dependency cache
          paths:
            - .npm
            # Cypress installs to ~/.cache
            - ~/.cache
          key: v1-dependencies-cache
      - save_cache:
          # Save the nx/ng computational caches
          paths:
            # Cache location of the nx command
            - node_modules/.cache
            # Cache location of the ng command
            - .angular
            # dist folder is needed to cache the actual output
            - dist
          key: v1-computational-cache
      - persist_to_workspace:
          root: .
          paths:
            - dist/*
            - VERSION
            - .npmrc
      - ms-teams/report:
          only_on_fail: true
          webhook_url: << pipeline.parameters.ms-teams-webhook >>

  deploy-frontend:
    executor: node-executor
    steps:
      - spinnaker-deployment:
          spinnaker-module: "frontend"
