# Config dedicated for module A
# All the resources must be prefixed with `module-a-` to avoid conflicts

version: 2.1

orbs:
  aws-ecr: circleci/aws-ecr@6.15.3

jobs:
  aws-dummy-frontend:
    steps:
      - run: echo "Frontend deploy"
    requires:
      - common-pre
  deploy-frontend:
    docker:
      - image: cimg/node:14.18.2
    steps:
      - run: echo "Deployed Frontend"
    requires:
      - aws-dummy-frontend

workflows:
  frontend-workflow:
    jobs:
      - common-pre
      - aws-dummy-frontend:
        requires:
          - common-pre
      - deploy-frontend:
          requires:
            - aws-dummy-frontend
