version: 2.1

orbs:
  sonarcloud: sonarsource/sonarcloud@1.0.1
  lighthouse-check: foo-software/lighthouse-check@0.0.13

jobs:
  build:
    docker:
      - image: circleci/node:14
    steps:
      - checkout
      - sonarcloud/scan
  lighthouse-test:
    docker:
      - image: cimg/base:stable
    steps:
      - lighthouse-check/audit

workflows:
  main:
    jobs:
      - build:
          context: SonarCloud
      - lighthouse-test