version: 2.1

setup: true

orbs:

  config-splitting:

    orbs:
      continuation: circleci/continuation@0.1.2

    commands:

    jobs:


# Common jobs for the main workflows
jobs:
  common-pre:
    docker:
      - image: cimg/node:14.18.2
    steps:
      - run: echo 'This would be the build process'

workflows:
  setup-workflow:
    jobs:
      - config-splitting/setup-dynamic-config:
          base-revision: main
          modules: |
            backend
            frontend