version: 2.1

orbs:
  sonarcloud: sonarsource/sonarcloud@1.0.2

jobs:
  build:
    docker:
      - image: circleci/node:14
    steps:
      - checkout
      - sonarcloud/scan

workflows:
  main:
    jobs:
      - build:
          context: sonarcloud
