version: 2.1

setup: true

orbs:

  config-splitting:

    orbs:
      continuation: circleci/continuation@0.1.2

    commands:
      check-for-changes:
        steps:
          - run: echo "Call script, make nx affected check and build config yml"
        merge-modular-configs:
          parameters:
            modules:
              description: Path to the file for the list of the modules to build
              type: string
              default: /tmp/modules-filtered.txt
            shared-config:
              description: Path to the config providing shared resources (such as prerequisite jobs and common commands)
              type: string
              default: .circleci/config.yml
            continue-config:
              description: Path to the internally-used config for continuation
              type: string
              default: .circleci/continue-config.yml
          steps:
            - run:
                name: Merge configs
                command: |
                  # If `modules` is unavailable, stop this job without continuation
                  if [ ! -f "<< parameters.modules >>" ] || [ ! -s "<< parameters.modules >>" ]
                  then
                    echo 'Nothing to merge. Halting the job.'
                    circleci-agent step halt
                    exit
                  fi

                  # Convert a list of dirs to a list of config.yml
                  sed -i -e 's/$/\/.circleci\/config.yml/g' "<< parameters.modules >>"

                  # If `shared-config` exists, append it at the end of `modules`
                  if [ -f << parameters.shared-config >> ]
                  then
                    echo "<< parameters.shared-config >>" >> "<< parameters.modules >>"
                  fi

                  xargs -a "<< parameters.modules >>" yq -y -s 'reduce .[] as $item ({}; . * $item)' | tee "<< parameters.continue-config >>"

    jobs:
      setup-dynamic-config:
        docker:
          - image: cimg/node:14.18.2
        steps:
          - check-for-changes
          - merge-modular-configs
          - continuation/continue:
            configuration_path: << parameters.continue-config >>
            parameters: '{"run-setup":false}'


# Common jobs for the main workflows
jobs:
  common-pre:
    docker:
      - image: cimg/node:14.18.2
    steps:
      - run: echo 'This would be the build process'

workflows:
  setup-workflow:
    jobs:
      - config-splitting/setup-dynamic-config:
          base-revision: main
          modules: |
            backend
            frontend