version: 2.1

setup: true

orbs:
  config-splitting:
    orbs:
      continuation: circleci/continuation@0.1.2

    commands:
      check-for-changes-merge-configs:
        steps:
          - run: |
              chmod +x ./dynamic_pipeline/generate-pipeline-config
              ./dynamic_pipeline/generate-pipeline-config
              
    jobs:
      setup-dynamic-config:
        docker:
          - image: cimg/node:14.18.2
        steps:
          - checkout
          - run:
              command: npm ci
          - run:
              command: npm build
          - run:
          name: Store the version
            command: |
              export BUILD_VERSION=$(git rev-parse --abbrev-ref HEAD)-$(git rev-parse --short HEAD)
              echo "$BUILD_VERSION-$CIRCLE_BUILD_NUM" > VERSION
              echo "Stored version " `cat VERSION`
          - save_cache:
              paths:
                - dist
              key: v1-dist-cache-<< BUILD_VERSION >>
          - check-for-changes-merge-configs
          - continuation/continue:
              configuration_path: ./dynamic_pipeline/configs/generated_config.yml

workflows:
  setup-workflow:
    jobs:
      - config-splitting/setup-dynamic-config
