version: 2.1

orbs:
  sonarcloud: sonarsource/sonarcloud@1.0.1
  browser-tools: circleci/browser-tools@1.2.3
  github-cli: circleci/github-cli@1.0.5
  
jobs:
  build:
    docker:
      - image: cimg/node:14.18.2-browsers
    steps:
      - checkout
      - sonarcloud/scan
      - run:
          name: NPM Install
          command: npm install
      - run:
          name: Build
          command: npm run build
      - run:  
          name: Install lhci 
          command: sudo npm install -g @lhci/cli@0.8.x
      - browser-tools/install-chrome
      - browser-tools/install-chromedriver
      - run: 
          name: Run lhci
          command: lhci autorun

workflows:
  main:
    jobs:
      #- build:
      #    context: SonarCloud
      - github-cli/release:
          tag: 1.0.0
          title: test tag
          #requires: 
          #  - build
          context:
            - SonarCloud