version: 2.1

orbs:
  sonarcloud: sonarsource/sonarcloud@1.0.1

jobs:
  build:
    docker:
      - image: circleci/node:14
    steps:
      - checkout
      - sonarcloud/scan
      - run:
          name: NPM Install
          command: npm install
      - run:
          name: Build
          command: npm run build
      - run:
          name: Lighthouse
          command: npm run lighthouse

workflows:
  main:
    jobs:
      - build:
          context: SonarCloud
