version: 2.1

orbs:
  sonarcloud: sonarsource/sonarcloud@1.0.1

jobs:
  build:
    docker:
      - image: circleci/node:14
    steps:
      - checkout
      - sonarcloud/scan
  lighthouse:
    docker:
      - image: circleci/node:14
    steps:
      - run:
          name: build
          command: npm run build
      - run:
          name: lighthouse
          command: npm run lighthouse

workflows:
  main:
    jobs:
      - build:
          context: SonarCloud
      - lighthouse
