version: 2.1

workflows:
  ci:
    jobs:
      - flow:
          context:
            - cypress

workflows:
  version: 2
  build:
    when: ${CIRCLE_PULL_REQUEST##*/}
      - build
  deploy:
    - deploay

jobs:
  build:
    docker:
      - image: cypress/base:16.14.0
    steps:
     - checkout
     - run: echo 'Build'
  deploy:
    docker:
      - image: cypress/base:16.14.0
    steps:
     - checkout
     - run: echo 'Deploy'