version: 2.1

workflows:
  version: 2
  build:
    when: ${CIRCLE_PULL_REQUEST##*/}
    jobs:
      - build
  deploy:
    when: 
      or:
        - equal: [ main, << pipeline.git.branch >> ]
        - equal: [ staging, << pipeline.git.branch >> ]
    jobs:
      - deploy

jobs:
  build:
    docker:
      - image: cypress/base:16.14.0
    steps:
     - checkout
     - run: echo 'Build'
  deploy:
    docker:
      - image: cypress/base:16.14.0
    steps:
     - checkout
     - run: echo 'Deploy'