version: 2.1

setup: true

orbs:
  continuation: circleci/continuation@0.1.0


# Common jobs for the main workflows
jobs:
  common-pre:
    docker:
      - image: cimg/node:14.18.2
    steps:
      - run: echo 'Jobs with `common-` prefix are intended to be shared among modules'

workflows:
  setup-workflow:
    jobs:
      - config-splitting/setup-dynamic-config:
          force-all: << pipeline.parameters.force-all >>
          base-revision: main
          modules: |
            backend
            frontend