version: 2.1

workflows:
  version: 2
  ci:
    jobs:
      - flow

jobs:
  flow:
    docker:
      - image: cimg/node:16.14.0
    steps:
     - run:
        name: Define current base
        command: npm install