version: 2.1

orbs:
  sonarcloud: sonarsource/sonarcloud@1.0.1
  browser-tools: circleci/browser-tools@1.2.3
  
jobs:
  build:
    docker:
      - image: cimg/node:14.18.2
    steps:
      - checkout
      - sonarcloud/scan
      - run:
          name: NPM Install
          command: npm install
      - run:
          name: Build
          command: npm run build
      - save_cache:
          paths:
            - node_modules
            - .npm
            - dist
            - lighthouserc.js
          key: dependencies-cache-{{ checksum "dist" }}
  lighthouse:
      docker:
        - image: cimg/node:14.18.2-browsers   
      steps:
        - restore_cache:
            keys:
              - dependencies-cache-{{ checksum "dist" }}
        - run:  
            name: Install lhci 
            command: sudo npm install -g @lhci/cli@0.8.x
        - browser-tools/install-chrome
        - browser-tools/install-chromedriver
        - run: 
            name: Run lhci
            command: lhci autorun

workflows:
  main:
    jobs:
      - build:
          context: SonarCloud
      - lighthouse:
          requires: 
            - build