#!/bin/bash 
set -o pipefail

echo "Running script to generate pipeline config"

# install needed dependencies
npm ci

# check for changes affecting frontend / backend
frontend=false
backend=false
OUTPUT=$(nx affected:apps)
if [[ $OUTPUT == *"frontend"* ]]
then
    frontend=true
if [[ $OUTPUT == *"backend"* ]]
then
    backend=true
fi

# create new config.yml file for pipeline
cd dynamic_pipeline
mkdir configs/
touch configs/generated_config.yml

# fill config based on changes
cat elements/head.yml > configs/generated_config.yml
cat elements/build.yml >> configs/generated_config.yml
if [ $frontend == true ]
then
  cat elements/build_f.yml >> configs/generated_config.yml
fi
if [ $backend == true ]
then
  cat elements/build_b.yml >> configs/generated_config.yml
fi
cat elements/commands.yml >> configs/generated_config.yml
cat elements/jobs.yml >> configs/generated_config.yml

cat configs/generated_config.yml