#!/bin/bash 
set -o pipefail

echo "Running script to generate pipeline config"

# check for changes affecting frontend / backend
#OUTPUT=$(nx affected:apps)
OUTPUT="frontend/backend" 

# create new config.yml file for pipeline
cd dynamic_pipeline
mkdir configs/
touch configs/generated_config.yml

# fill config based on changes
cat elements/head.yml > configs/generated_config.yml
cat elements/build.yml >> configs/generated_config.yml
if [[ $OUTPUT == *"frontend"* ]]
then
    cat elements/build_f.yml >> configs/generated_config.yml
fi
if [[ $OUTPUT == *"backend"* ]]
then
    cat elements/build_b.yml >> configs/generated_config.yml
fi
cat elements/jobs.yml >> configs/generated_config.yml

cat configs/generated_config.yml
