workflows:
  version: 2
  contentpool2-ci:
    jobs:
      - build:
          <<: *base_build_job_config
      - lighthouse-check:
          <<: *base_build_job_config
          requires:
            - build