jobs:
  build:
    executor: node-executor
    steps:
      - checkout
      - run:
          command: npm ci
      - run:
          command: npm run-script build
      - save_cache:
          paths:
            - dist
          key: test-{{ epoch }}
      - run:
          name: Define current base
          command: echo "build test"

  deploy-backend:
    executor: node-executor
    steps:
      - run: echo "dep backend"

  deploy-frontend:
    executor: node-executor
    steps:
      - run: echo "dep frontend"
  
  lighthouse-check:
    docker:
      - image: cimg/node:14.18.2-browsers # own image for browser support
    steps:
      - checkout
      - restore_cache:
          keys:
            - test
      - run: ls -la -R ./dist
      - run:  
          name: Install lhci 
          command: sudo npm install -g @lhci/cli@0.8.x
      - browser-tools/install-chrome
      - browser-tools/install-chromedriver
      - run: 
          name: Run lhci
          command: lhci autorun

