# Config dedicated for module A
# All the resources must be prefixed with `module-a-` to avoid conflicts

version: 2.1

orbs:
  aws-ecr: circleci/aws-ecr@6.15.3

jobs:
  aws-dummy-backend:
    steps:
      - run: echo "Backed deploy"
  deploy-backend:
    docker:
      - image: cimg/node:14.18.2
    steps:
      - run: echo "Deployed Backend"

workflows:
  backend-workflow:
    jobs:
      - common-pre
      - aws-dummy-backend:
        requires:
          - common-pre
      - deploy-backend:
          requires:
            - aws-dummy-backend